name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "36989625ad33411a950afc52e8d62f61" },
  { binding = "SHARE", id = "d06db27c8fb44ffaba3dc994156b8cd0" }
]